//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UyumYemekSipariş.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int FavoriteID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
    }
}
